// Generated by CoffeeScript 1.3.3
var makeDataRows;

makeDataRows = function(data) {
  var row, _i, _len;
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    row = data[_i];
    $("#content").prepend($(ich.rowtemplate(row)));
  }
  return $('#content').isotope({
    itemSelector: '.dataset-row',
    layoutMode: 'fitRows'
  });
};
